// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.squareup.capital.common.AWSStepFunctionTaskData', null, global);
goog.exportSymbol('proto.squareup.capital.common.BusinessEntityType', null, global);
goog.exportSymbol('proto.squareup.capital.common.LoanDepositLocation', null, global);
goog.exportSymbol('proto.squareup.capital.common.MaturityTermUnit', null, global);
goog.exportSymbol('proto.squareup.capital.common.Originator', null, global);
goog.exportSymbol('proto.squareup.capital.common.Pagination', null, global);
goog.exportSymbol('proto.squareup.capital.common.PaymentPeriod', null, global);
goog.exportSymbol('proto.squareup.capital.common.Product', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.capital.common.Pagination = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.squareup.capital.common.Pagination, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.capital.common.Pagination.displayName = 'proto.squareup.capital.common.Pagination';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.capital.common.AWSStepFunctionTaskData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.squareup.capital.common.AWSStepFunctionTaskData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.capital.common.AWSStepFunctionTaskData.displayName = 'proto.squareup.capital.common.AWSStepFunctionTaskData';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.capital.common.Pagination.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.capital.common.Pagination.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.capital.common.Pagination} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.capital.common.Pagination.toObject = function(includeInstance, msg) {
  var f, obj = {
    cursor: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    maxResults: jspb.Message.getFieldWithDefault(msg, 2, 20)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.capital.common.Pagination}
 */
proto.squareup.capital.common.Pagination.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.capital.common.Pagination;
  return proto.squareup.capital.common.Pagination.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.capital.common.Pagination} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.capital.common.Pagination}
 */
proto.squareup.capital.common.Pagination.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxResults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.capital.common.Pagination.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.capital.common.Pagination.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.capital.common.Pagination} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.capital.common.Pagination.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional string cursor = 1;
 * @return {string}
 */
proto.squareup.capital.common.Pagination.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.capital.common.Pagination} returns this
 */
proto.squareup.capital.common.Pagination.prototype.setCursor = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.capital.common.Pagination} returns this
 */
proto.squareup.capital.common.Pagination.prototype.clearCursor = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.capital.common.Pagination.prototype.hasCursor = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 max_results = 2;
 * @return {number}
 */
proto.squareup.capital.common.Pagination.prototype.getMaxResults = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 20));
};


/**
 * @param {number} value
 * @return {!proto.squareup.capital.common.Pagination} returns this
 */
proto.squareup.capital.common.Pagination.prototype.setMaxResults = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.capital.common.Pagination} returns this
 */
proto.squareup.capital.common.Pagination.prototype.clearMaxResults = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.capital.common.Pagination.prototype.hasMaxResults = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.capital.common.AWSStepFunctionTaskData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.capital.common.AWSStepFunctionTaskData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.toObject = function(includeInstance, msg) {
  var f, obj = {
    taskId: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    executionArn: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.capital.common.AWSStepFunctionTaskData;
  return proto.squareup.capital.common.AWSStepFunctionTaskData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.capital.common.AWSStepFunctionTaskData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setExecutionArn(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.capital.common.AWSStepFunctionTaskData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.capital.common.AWSStepFunctionTaskData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string task_id = 1;
 * @return {string}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.getTaskId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData} returns this
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.setTaskId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData} returns this
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.clearTaskId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.hasTaskId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string execution_arn = 2;
 * @return {string}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.getExecutionArn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData} returns this
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.setExecutionArn = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.capital.common.AWSStepFunctionTaskData} returns this
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.clearExecutionArn = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.capital.common.AWSStepFunctionTaskData.prototype.hasExecutionArn = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * @enum {number}
 */
proto.squareup.capital.common.BusinessEntityType = {
  BET_DO_NOT_USE: 0,
  SOLE_PROPRIETORSHIP: 1,
  C_CORPORATION: 2,
  S_CORPORATION: 3,
  LIMITED_LIABILITY_COMPANY: 4,
  PARTNERSHIP: 5,
  COOPERATIVE: 6,
  INDEPENDENT_CONTRACTOR: 7,
  SELF_EMPLOYED: 8,
  NONPROFIT: 9,
  VETERANS_ORGANIZATION: 10,
  TRIBAL_BUSINESS: 11,
  OTHER: 12,
  CORPORATION: 13
};

/**
 * @enum {number}
 */
proto.squareup.capital.common.Originator = {
  O_DO_NOT_USE: 0,
  CELTIC: 1,
  SQUARE: 2,
  SQUARE_CAPITAL: 3,
  SQUARE_AUSTRALIA: 4,
  SQUARE_FINANCIAL_SERVICES: 5,
  SQUARE_CANADA: 6
};

/**
 * @enum {number}
 */
proto.squareup.capital.common.PaymentPeriod = {
  PP_DO_NOT_USE: 0,
  DAILY: 1,
  WEEKLY: 2,
  MONTHLY: 3
};

/**
 * @enum {number}
 */
proto.squareup.capital.common.MaturityTermUnit = {
  DU_DO_NOT_USE: 0,
  DAY: 1,
  MONTH: 2
};

/**
 * @enum {number}
 */
proto.squareup.capital.common.Product = {
  P_DO_NOT_USE: 0,
  BUSINESS_FLEX: 1,
  BUSINESS_TXD: 2,
  INSTALLMENTS_INSTORE: 3,
  INSTALLMENTS_INVOICE: 4,
  INSTALLMENTS_ECOMMERCE: 5
};

/**
 * @enum {number}
 */
proto.squareup.capital.common.LoanDepositLocation = {
  LDL_DO_NOT_USE: 0,
  LINKED_BANK_ACCOUNT: 1,
  SQUARE_BALANCE: 2
};

goog.object.extend(exports, proto.squareup.capital.common);
