// source: error.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_descriptor_pb = require('google-protobuf/google/protobuf/descriptor_pb.js');
goog.object.extend(proto, google_protobuf_descriptor_pb);
var validation_pb = require('./validation_pb.js');
goog.object.extend(proto, validation_pb);
var options_pb = require('./options_pb.js');
goog.object.extend(proto, options_pb);
goog.exportSymbol('proto.squareup.connect.v2.resources.Error', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.Error.Category', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.Error.Code', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.ErrorResponse', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.MethodErrorCodes', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.errorCategory', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.errorCodeGeneric', null, global);
goog.exportSymbol('proto.squareup.connect.v2.resources.methodErrorCodes', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.connect.v2.resources.MethodErrorCodes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.squareup.connect.v2.resources.MethodErrorCodes.repeatedFields_, null);
};
goog.inherits(proto.squareup.connect.v2.resources.MethodErrorCodes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.connect.v2.resources.MethodErrorCodes.displayName = 'proto.squareup.connect.v2.resources.MethodErrorCodes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.connect.v2.resources.Error = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.squareup.connect.v2.resources.Error, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.connect.v2.resources.Error.displayName = 'proto.squareup.connect.v2.resources.Error';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.connect.v2.resources.ErrorResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.squareup.connect.v2.resources.ErrorResponse.repeatedFields_, null);
};
goog.inherits(proto.squareup.connect.v2.resources.ErrorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.connect.v2.resources.ErrorResponse.displayName = 'proto.squareup.connect.v2.resources.ErrorResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.connect.v2.resources.MethodErrorCodes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.connect.v2.resources.MethodErrorCodes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.toObject = function(includeInstance, msg) {
  var f, obj = {
    valueList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.connect.v2.resources.MethodErrorCodes}
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.connect.v2.resources.MethodErrorCodes;
  return proto.squareup.connect.v2.resources.MethodErrorCodes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.connect.v2.resources.MethodErrorCodes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.connect.v2.resources.MethodErrorCodes}
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<!proto.squareup.connect.v2.resources.Error.Code>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addValue(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.connect.v2.resources.MethodErrorCodes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.connect.v2.resources.MethodErrorCodes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValueList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      1,
      f
    );
  }
};


/**
 * repeated Error.Code value = 1;
 * @return {!Array<!proto.squareup.connect.v2.resources.Error.Code>}
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.getValueList = function() {
  return /** @type {!Array<!proto.squareup.connect.v2.resources.Error.Code>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<!proto.squareup.connect.v2.resources.Error.Code>} value
 * @return {!proto.squareup.connect.v2.resources.MethodErrorCodes} returns this
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.setValueList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!proto.squareup.connect.v2.resources.Error.Code} value
 * @param {number=} opt_index
 * @return {!proto.squareup.connect.v2.resources.MethodErrorCodes} returns this
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.addValue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.squareup.connect.v2.resources.MethodErrorCodes} returns this
 */
proto.squareup.connect.v2.resources.MethodErrorCodes.prototype.clearValueList = function() {
  return this.setValueList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.connect.v2.resources.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.connect.v2.resources.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.connect.v2.resources.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
    category: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    code: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    detail: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    field: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.connect.v2.resources.Error}
 */
proto.squareup.connect.v2.resources.Error.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.connect.v2.resources.Error;
  return proto.squareup.connect.v2.resources.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.connect.v2.resources.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.connect.v2.resources.Error}
 */
proto.squareup.connect.v2.resources.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 4:
      var value = /** @type {!proto.squareup.connect.v2.resources.Error.Category} */ (reader.readEnum());
      msg.setCategory(value);
      break;
    case 1:
      var value = /** @type {!proto.squareup.connect.v2.resources.Error.Code} */ (reader.readEnum());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.connect.v2.resources.Error.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.connect.v2.resources.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.connect.v2.resources.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.squareup.connect.v2.resources.Error.Category} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = /** @type {!proto.squareup.connect.v2.resources.Error.Code} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.squareup.connect.v2.resources.Error.Category = {
  API_ERROR: 1,
  AUTHENTICATION_ERROR: 2,
  INVALID_REQUEST_ERROR: 3,
  RATE_LIMIT_ERROR: 4,
  PAYMENT_METHOD_ERROR: 5,
  REFUND_ERROR: 6,
  MERCHANT_SUBSCRIPTION_ERROR: 7
};

/**
 * @enum {number}
 */
proto.squareup.connect.v2.resources.Error.Code = {
  INTERNAL_SERVER_ERROR: 5000000,
  UNAUTHORIZED: 4010000,
  ACCESS_TOKEN_EXPIRED: 4010001,
  ACCESS_TOKEN_REVOKED: 4010002,
  CLIENT_DISABLED: 4010003,
  FORBIDDEN: 4030000,
  INSUFFICIENT_SCOPES: 4030001,
  APPLICATION_DISABLED: 4030002,
  V1_APPLICATION: 4030003,
  V1_ACCESS_TOKEN: 4030004,
  CARD_PROCESSING_NOT_ENABLED: 4030005,
  MERCHANT_SUBSCRIPTION_NOT_FOUND: 4030006,
  BAD_REQUEST: 4000000,
  MISSING_REQUIRED_PARAMETER: 4000001,
  INCORRECT_TYPE: 4000002,
  INVALID_TIME: 4000003,
  INVALID_TIME_RANGE: 4000004,
  INVALID_VALUE: 4000005,
  INVALID_CURSOR: 4000006,
  UNKNOWN_QUERY_PARAMETER: 4000007,
  CONFLICTING_PARAMETERS: 4000008,
  EXPECTED_JSON_BODY: 4000009,
  INVALID_SORT_ORDER: 4000010,
  VALUE_REGEX_MISMATCH: 4000061,
  VALUE_TOO_SHORT: 4000057,
  VALUE_TOO_LONG: 4000011,
  VALUE_TOO_LOW: 4000012,
  VALUE_TOO_HIGH: 4000058,
  VALUE_EMPTY: 4000059,
  ARRAY_LENGTH_TOO_LONG: 4000073,
  ARRAY_LENGTH_TOO_SHORT: 4000074,
  ARRAY_EMPTY: 4000060,
  EXPECTED_BOOLEAN: 4000013,
  EXPECTED_INTEGER: 4000014,
  EXPECTED_FLOAT: 4000015,
  EXPECTED_STRING: 4000016,
  EXPECTED_OBJECT: 4000017,
  EXPECTED_ARRAY: 4000018,
  EXPECTED_MAP: 4000079,
  EXPECTED_BASE64_ENCODED_BYTE_ARRAY: 4000056,
  INVALID_ARRAY_VALUE: 4000019,
  INVALID_ENUM_VALUE: 4000020,
  INVALID_CONTENT_TYPE: 4000021,
  INVALID_FORM_VALUE: 4000022,
  CUSTOMER_NOT_FOUND: 4000023,
  BUYER_NOT_FOUND: 4000121,
  ONE_INSTRUMENT_EXPECTED: 4000052,
  NO_FIELDS_SET: 4000053,
  DEPRECATED_FIELD_SET: 4000078,
  RETIRED_FIELD_SET: 4000103,
  TOO_MANY_MAP_ENTRIES: 4000108,
  MAP_KEY_LENGTH_TOO_SHORT: 4000109,
  MAP_KEY_LENGTH_TOO_LONG: 4000110,
  CUSTOMER_MISSING_NAME: 4000122,
  CUSTOMER_MISSING_EMAIL: 4000123,
  INVALID_PAUSE_LENGTH: 4000124,
  INVALID_DATE: 4000125,
  CARD_EXPIRED: 4000024,
  INVALID_EXPIRATION: 4000027,
  INVALID_EXPIRATION_YEAR: 4000028,
  INVALID_EXPIRATION_DATE: 4000039,
  UNSUPPORTED_CARD_BRAND: 4000055,
  UNSUPPORTED_ENTRY_METHOD: 4000076,
  INVALID_ENCRYPTED_CARD: 4000081,
  INVALID_CARD: 4000040,
  GENERIC_DECLINE: 4000082,
  CVV_FAILURE: 4000083,
  ADDRESS_VERIFICATION_FAILURE: 4000084,
  INVALID_ACCOUNT: 4000085,
  CURRENCY_MISMATCH: 4000086,
  INSUFFICIENT_FUNDS: 4000087,
  INSUFFICIENT_PERMISSIONS: 4000088,
  CARDHOLDER_INSUFFICIENT_PERMISSIONS: 4000089,
  INVALID_LOCATION: 4000090,
  TRANSACTION_LIMIT: 4000091,
  VOICE_FAILURE: 4000092,
  PAN_FAILURE: 4000093,
  EXPIRATION_FAILURE: 4000094,
  CARD_NOT_SUPPORTED: 4000095,
  INVALID_PIN: 4000096,
  MISSING_PIN: 4000119,
  MISSING_ACCOUNT_TYPE: 4000120,
  INVALID_POSTAL_CODE: 4000097,
  INVALID_FEES: 4000098,
  MANUALLY_ENTERED_PAYMENT_NOT_SUPPORTED: 4000099,
  PAYMENT_LIMIT_EXCEEDED: 4000100,
  GIFT_CARD_AVAILABLE_AMOUNT: 4000106,
  ACCOUNT_UNUSABLE: 4000117,
  BUYER_REFUSED_PAYMENT: 4000118,
  DELAYED_TRANSACTION_EXPIRED: 4000041,
  DELAYED_TRANSACTION_CANCELED: 4000042,
  DELAYED_TRANSACTION_CAPTURED: 4000043,
  DELAYED_TRANSACTION_FAILED: 4000044,
  CARD_TOKEN_EXPIRED: 4000045,
  CARD_TOKEN_USED: 4000046,
  AMOUNT_TOO_HIGH: 4000047,
  UNSUPPORTED_INSTRUMENT_TYPE: 4000054,
  REFUND_AMOUNT_INVALID: 4000048,
  REFUND_ALREADY_PENDING: 4000049,
  PAYMENT_NOT_REFUNDABLE: 4000050,
  REFUND_DECLINED: 4000112,
  INVALID_CARD_DATA: 4000051,
  SOURCE_USED: 4000113,
  SOURCE_EXPIRED: 4000114,
  UNSUPPORTED_LOYALTY_REWARD_TIER: 4000115,
  LOCATION_MISMATCH: 4000077,
  ORDER_EXPIRED: 4000062,
  ORDER_ALREADY_USED: 4000067,
  ORDER_TOO_MANY_CATALOG_OBJECTS: 4000072,
  INSUFFICIENT_INVENTORY: 4000063,
  PRICE_MISMATCH: 4000064,
  VERSION_MISMATCH: 4000065,
  IDEMPOTENCY_KEY_REUSED: 4000066,
  UNEXPECTED_VALUE: 4000068,
  SANDBOX_NOT_SUPPORTED: 4000069,
  INVALID_EMAIL_ADDRESS: 4000070,
  INVALID_PHONE_NUMBER: 4000075,
  CHECKOUT_EXPIRED: 4000071,
  BAD_CERTIFICATE: 4000080,
  INVALID_SQUARE_VERSION_FORMAT: 4000101,
  API_VERSION_INCOMPATIBLE: 4000102,
  INVALID_URL: 4000104,
  HTTPS_ONLY: 4000105,
  UNREACHABLE_URL: 4000107,
  SESSION_EXPIRED: 4000111,
  CARD_DECLINED: 4020001,
  VERIFY_CVV_FAILURE: 4020002,
  VERIFY_AVS_FAILURE: 4020003,
  CARD_DECLINED_CALL_ISSUER: 4020004,
  CARD_DECLINED_VERIFICATION_REQUIRED: 4020005,
  BAD_EXPIRATION: 4020006,
  CHIP_INSERTION_REQUIRED: 4020007,
  ALLOWABLE_PIN_TRIES_EXCEEDED: 4020008,
  RESERVATION_DECLINED: 4020009,
  BLOCKED_BY_BLOCKLIST: 4020010,
  NOT_FOUND: 4040000,
  APPLE_PAYMENT_PROCESSING_CERTIFICATE_HASH_NOT_FOUND: 4040001,
  METHOD_NOT_ALLOWED: 4050000,
  NOT_ACCEPTABLE: 4060000,
  REQUEST_TIMEOUT: 4080000,
  CONFLICT: 4090000,
  GONE: 4100000,
  REQUEST_ENTITY_TOO_LARGE: 4130000,
  UNSUPPORTED_MEDIA_TYPE: 4150000,
  UNPROCESSABLE_ENTITY: 4220000,
  RATE_LIMITED: 4290000,
  CLIENT_CLOSED_REQUEST: 4990000,
  NOT_IMPLEMENTED: 5010000,
  BAD_GATEWAY: 5020000,
  SERVICE_UNAVAILABLE: 5030000,
  TEMPORARY_ERROR: 5030001,
  GATEWAY_TIMEOUT: 5040000
};

/**
 * optional Category category = 4;
 * @return {!proto.squareup.connect.v2.resources.Error.Category}
 */
proto.squareup.connect.v2.resources.Error.prototype.getCategory = function() {
  return /** @type {!proto.squareup.connect.v2.resources.Error.Category} */ (jspb.Message.getFieldWithDefault(this, 4, 1));
};


/**
 * @param {!proto.squareup.connect.v2.resources.Error.Category} value
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.setCategory = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.clearCategory = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.connect.v2.resources.Error.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional Code code = 1;
 * @return {!proto.squareup.connect.v2.resources.Error.Code}
 */
proto.squareup.connect.v2.resources.Error.prototype.getCode = function() {
  return /** @type {!proto.squareup.connect.v2.resources.Error.Code} */ (jspb.Message.getFieldWithDefault(this, 1, 5000000));
};


/**
 * @param {!proto.squareup.connect.v2.resources.Error.Code} value
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.setCode = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.clearCode = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.connect.v2.resources.Error.prototype.hasCode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string detail = 2;
 * @return {string}
 */
proto.squareup.connect.v2.resources.Error.prototype.getDetail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.setDetail = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.clearDetail = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.connect.v2.resources.Error.prototype.hasDetail = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string field = 3;
 * @return {string}
 */
proto.squareup.connect.v2.resources.Error.prototype.getField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.setField = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.connect.v2.resources.Error} returns this
 */
proto.squareup.connect.v2.resources.Error.prototype.clearField = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.connect.v2.resources.Error.prototype.hasField = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.squareup.connect.v2.resources.ErrorResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.connect.v2.resources.ErrorResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.connect.v2.resources.ErrorResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.connect.v2.resources.ErrorResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.ErrorResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    errorsList: jspb.Message.toObjectList(msg.getErrorsList(),
    proto.squareup.connect.v2.resources.Error.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.connect.v2.resources.ErrorResponse}
 */
proto.squareup.connect.v2.resources.ErrorResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.connect.v2.resources.ErrorResponse;
  return proto.squareup.connect.v2.resources.ErrorResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.connect.v2.resources.ErrorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.connect.v2.resources.ErrorResponse}
 */
proto.squareup.connect.v2.resources.ErrorResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.squareup.connect.v2.resources.Error;
      reader.readMessage(value,proto.squareup.connect.v2.resources.Error.deserializeBinaryFromReader);
      msg.addErrors(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.connect.v2.resources.ErrorResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.connect.v2.resources.ErrorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.connect.v2.resources.ErrorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.connect.v2.resources.ErrorResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getErrorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.squareup.connect.v2.resources.Error.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Error errors = 1;
 * @return {!Array<!proto.squareup.connect.v2.resources.Error>}
 */
proto.squareup.connect.v2.resources.ErrorResponse.prototype.getErrorsList = function() {
  return /** @type{!Array<!proto.squareup.connect.v2.resources.Error>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.squareup.connect.v2.resources.Error, 1));
};


/**
 * @param {!Array<!proto.squareup.connect.v2.resources.Error>} value
 * @return {!proto.squareup.connect.v2.resources.ErrorResponse} returns this
*/
proto.squareup.connect.v2.resources.ErrorResponse.prototype.setErrorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.squareup.connect.v2.resources.Error=} opt_value
 * @param {number=} opt_index
 * @return {!proto.squareup.connect.v2.resources.Error}
 */
proto.squareup.connect.v2.resources.ErrorResponse.prototype.addErrors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.squareup.connect.v2.resources.Error, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.squareup.connect.v2.resources.ErrorResponse} returns this
 */
proto.squareup.connect.v2.resources.ErrorResponse.prototype.clearErrorsList = function() {
  return this.setErrorsList([]);
};



/**
 * A tuple of {field number, class constructor} for the extension
 * field named `methodErrorCodes`.
 * @type {!jspb.ExtensionFieldInfo<!proto.squareup.connect.v2.resources.MethodErrorCodes>}
 */
proto.squareup.connect.v2.resources.methodErrorCodes = new jspb.ExtensionFieldInfo(
    60016,
    {methodErrorCodes: 0},
    proto.squareup.connect.v2.resources.MethodErrorCodes,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         proto.squareup.connect.v2.resources.MethodErrorCodes.toObject),
    0);

google_protobuf_descriptor_pb.MethodOptions.extensionsBinary[60016] = new jspb.ExtensionFieldBinaryInfo(
    proto.squareup.connect.v2.resources.methodErrorCodes,
    jspb.BinaryReader.prototype.readMessage,
    jspb.BinaryWriter.prototype.writeMessage,
    proto.squareup.connect.v2.resources.MethodErrorCodes.serializeBinaryToWriter,
    proto.squareup.connect.v2.resources.MethodErrorCodes.deserializeBinaryFromReader,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.MethodOptions.extensions[60016] = proto.squareup.connect.v2.resources.methodErrorCodes;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `errorCategory`.
 * @type {!jspb.ExtensionFieldInfo<!proto.squareup.connect.v2.resources.Error.Category>}
 */
proto.squareup.connect.v2.resources.errorCategory = new jspb.ExtensionFieldInfo(
    60000,
    {errorCategory: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.EnumValueOptions.extensionsBinary[60000] = new jspb.ExtensionFieldBinaryInfo(
    proto.squareup.connect.v2.resources.errorCategory,
    jspb.BinaryReader.prototype.readEnum,
    jspb.BinaryWriter.prototype.writeEnum,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumValueOptions.extensions[60000] = proto.squareup.connect.v2.resources.errorCategory;


/**
 * A tuple of {field number, class constructor} for the extension
 * field named `errorCodeGeneric`.
 * @type {!jspb.ExtensionFieldInfo<boolean>}
 */
proto.squareup.connect.v2.resources.errorCodeGeneric = new jspb.ExtensionFieldInfo(
    60004,
    {errorCodeGeneric: 0},
    null,
     /** @type {?function((boolean|undefined),!jspb.Message=): !Object} */ (
         null),
    0);

google_protobuf_descriptor_pb.EnumValueOptions.extensionsBinary[60004] = new jspb.ExtensionFieldBinaryInfo(
    proto.squareup.connect.v2.resources.errorCodeGeneric,
    jspb.BinaryReader.prototype.readBool,
    jspb.BinaryWriter.prototype.writeBool,
    undefined,
    undefined,
    false);
// This registers the extension field with the extended class, so that
// toObject() will function correctly.
google_protobuf_descriptor_pb.EnumValueOptions.extensions[60004] = proto.squareup.connect.v2.resources.errorCodeGeneric;

goog.object.extend(exports, proto.squareup.connect.v2.resources);
