// source: universal_token.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.squareup.common.universaltoken.UniversalToken', null, global);
goog.exportSymbol('proto.squareup.common.universaltoken.UniversalToken.Type', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.squareup.common.universaltoken.UniversalToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.squareup.common.universaltoken.UniversalToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.squareup.common.universaltoken.UniversalToken.displayName = 'proto.squareup.common.universaltoken.UniversalToken';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.toObject = function(opt_includeInstance) {
  return proto.squareup.common.universaltoken.UniversalToken.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.squareup.common.universaltoken.UniversalToken} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.common.universaltoken.UniversalToken.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    token: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.squareup.common.universaltoken.UniversalToken}
 */
proto.squareup.common.universaltoken.UniversalToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.squareup.common.universaltoken.UniversalToken;
  return proto.squareup.common.universaltoken.UniversalToken.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.squareup.common.universaltoken.UniversalToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.squareup.common.universaltoken.UniversalToken}
 */
proto.squareup.common.universaltoken.UniversalToken.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.squareup.common.universaltoken.UniversalToken.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.squareup.common.universaltoken.UniversalToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.squareup.common.universaltoken.UniversalToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.squareup.common.universaltoken.UniversalToken.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.squareup.common.universaltoken.UniversalToken.Type} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.squareup.common.universaltoken.UniversalToken.Type = {
  UNKNOWN: 0,
  LEGAL_ENTITY: 1,
  PLATFORM_ACCOUNT: 2,
  MERCHANT: 3,
  UNIT: 4,
  EMPLOYMENT: 5,
  PERSON: 6,
  APPLICATION: 7,
  CASH: 8,
  PAYMENT_CONFIGURATION: 9,
  SQUARE_LDAP: 10,
  DEVICE_CREDENTIAL_TOKEN: 11,
  CAPITAL_CUSTOMER_TOKEN: 12,
  PAYMENT_TOKEN: 13,
  REGULATOR_CASE_TOKEN: 14,
  SELLER_ACCOUNT_TOKEN: 15,
  PERMISSIONS_GROUP_TOKEN: 16,
  PERMISSIONS_POLICY_TOKEN: 17,
  PERMISSIONS_ROLE_TOKEN: 18,
  PERMISSIONS_RULE_TOKEN: 19
};

/**
 * optional Type type = 1;
 * @return {!proto.squareup.common.universaltoken.UniversalToken.Type}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.getType = function() {
  return /** @type {!proto.squareup.common.universaltoken.UniversalToken.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.squareup.common.universaltoken.UniversalToken.Type} value
 * @return {!proto.squareup.common.universaltoken.UniversalToken} returns this
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.setType = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.common.universaltoken.UniversalToken} returns this
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.clearType = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string token = 2;
 * @return {string}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.squareup.common.universaltoken.UniversalToken} returns this
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.setToken = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.squareup.common.universaltoken.UniversalToken} returns this
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.clearToken = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.squareup.common.universaltoken.UniversalToken.prototype.hasToken = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.squareup.common.universaltoken);
